import Head from "next/head";
import { Inter } from "@next/font/google";
import { getAllPostMeta } from "../lib/posts";
import Card from "../components/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>MI BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul className="">
          <div className="grid grid-cols-1 lg:col-start-2 lg:col-span-5 lg:grid-cols-3 gap-6">
            {posts.map((post, i) => (
              <div key={i}>
                <li>
                  <Card post={post} />
                </li>
              </div>
            ))}
          </div>
        </ul>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const posts = getAllPostMeta();

  return {
    props: {
      posts,
    },
  };
}
